### ISSUE TITLE
I am unable to install

### ISSUE THREAD

**Issue by lukexp** [m0n0l0c0/electron-router#15]
I am unable to install. He's sending it to a private directory on his github. The error in the created log record.
.
"install" "electron-router"
28 verbose node v10.15.3
29 verbose npm  v6.11.3
30 error code ENOENT
31 error syscall spawn git
32 error path git
33 error errno ENOENT
34 error enoent Error while executing:
34 error enoent undefined ls-remote -h -t https://github.com/m0n0l0c0/eventemitter3.git
34 error enoent
34 error enoent
34 error enoent spawn git ENOENT
35 error enoent This is related to npm not being able to find a file.
36 verbose exit [ 1, true ]

**Comment by lukexp** [comment]
the problem was git on windows, but getting it fixed. It is a tip for those who have the same problem.

**Comment by geblanco** [comment]
Hello @lukexp, thanks for reporting it anyway!
