### ISSUE TITLE
jest testing - router cannot be created

### ISSUE THREAD

**Issue by utillity** [m0n0l0c0/electron-router#3]
first of all thanks for the great module. I am using it in a multi-threaded (multi-window, but only the main window is visible) application which gathers information from various channels (IP, CAN-bus, etc.) and displays it in the UI.

When I test an object (using jest) which creates a router, Router(name) fails with the following error:

      at Router._isRenderProcess (node_modules/electron-router/router.js:153:20)
      at Router._setup (node_modules/electron-router/router.js:117:18)
      at Router (node_modules/electron-router/router.js:110:12)
      at node_modules/electron-router/router.js:440:17
      at new ChangeHandler (src/common/changeHandler.ts:22:20)
      at Object.it (__tests__/changeHandler.test.js:21:20)

it seems you access the `remote` object, which is not available in the JEST environment (since electron is not running). is there a way around this?

**Comment by m0n0l0c0** [comment]
Hi @utillity,

Thank you for your feedback, I'm glad to hear this module is useful to the community.

This module is intended to be run inside an electron environment and is really tied to it. There is not a clear way in which you can test it independently from electron, although it should be possible theoretically. In my opinion, there are various possibilities, I'll try to summarize them:
* Mock the necessary objects: this is probably the most difficult and unstable solution, you'd have to patch a big part of the remote object.
* Run the tests inside an electron environment: best, most stable solution, although probably not mature enough. There are various options here. I use mocha to run the tests of this modules, more specifically, a [fork](https://github.com/m0n0l0c0/electron-mocha) from the original project, it works reasonably well. I've done some research to do the same with jest and I found some interesting sources: [1](https://github.com/electron/electron/issues/3909) [2](https://github.com/facebook/jest/issues/3698) [3](https://github.com/nhunzaker/jest-electron-environment) [4](https://github.com/d4rkr00t/jest-electron-runner) [5](https://discuss.atom.io/t/unit-testing-electron-react-app-with-jest/48788).

I expect to this to be useful! :)
Please let me know which solution you take at the end or, even better, post it here so others can benefit from it.

Best,
Guillermo.

**Comment by utillity** [comment]
Hi, thanks for the feedback. Well, in my opinion the code could be made a little more robust to just detect that objects it requires are not initialized/available and it could throw an appropriate exception, or just throw errors when trying to send something. Thanks anyways. Tilli

**Comment by m0n0l0c0** [comment]
Yes, I totally agree that the code should handle that, and it does. The [first part](https://github.com/m0n0l0c0/electron-router/blob/master/router.js#L16) of the module does exactly that. To be more specific, if you are not running inside electron, the call to `require('electron')` should fail and the module throws an error for it, maybe jest is patching the require call?

**Comment by utillity** [comment]
Yes I saw that in your code. I don't know what that remote object is that fails, but there is no check

LG, Tilli
________________________________
