### ISSUE TITLE
Can not do redirect 

### ISSUE THREAD

**Issue by gasparyanyur** [m0n0l0c0/electron-router#5]
Hi all. In my `main.js` I have defined routes look like this
```
router.on('ready', () => {
        router.on('quit', () => {
        });
        router.on('register', (req, res) => {
            showTemplate(APP.Templates.Register);
        });
        router.on('login', (req, res) => {
            showTemplate(APP.Templates.Login);
        });
        router.on('logout', (req, res) => {
            storage.delete(API.UserIDKey);
            storage.delete(API.UserTokenKey);
            API_USER = {};
            router.send('login');
        });
        router.on('dashboard', (req, res) => {
            console.log(1);
            showTemplate(APP.Templates.Dashboard)
        });
        router.on('accounts', (req, res) => {
            getDashboard();
        });
    });
```

Than I am checking ,if the user has logined than redirect to the dashboard route
```
if (typeof API_USER.token !== 'undefined' && typeof API_USER.id !== 'undefined') {
        router.send('dashboard');
    } 
```

But the route sending is not working. Please help!

**Comment by m0n0l0c0** [comment]
Hi @gasparyanyur 

First, when using `router.send` method, there are no `(req, res)` parameters as it is simple communication, take a look to [that part of the api](https://github.com/m0n0l0c0/electron-router#simple-communication).

Now, let's check your code follows certain rules, please check this:
- [ ] All routes are declared when the electron app is ready (ie: inside the app.ready callback)
- [ ] The code inside the check for the API_USER runs (maybe a console log inside the if statement?)
- [ ] The `router.send('dashboard')` code gets called __after__ the routes declarations

Best,
Guillermo.

**Comment by gasparyanyur** [comment]
@m0n0l0c0 Thanks for reply.
I am using ejs templating so in my dashboard.ejs I have a code look like this 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Even Foundation - Dashboard</title>
    <link rel="stylesheet" href="../../styles/materialize.css">
    <script src="../../scripts/materialize.js"></script>
</head>
<body>
<div class="container-fluid">
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo left">EvenDex - Dashboard</a>
            <ul id="nav-mobile" class="right">
                <li><a href="#" onclick="getAddress()">Аккаунты</a></li>
                <li><a href="#" onclick="getDeals()">Торги</a></li>
                <li><a href="#" onclick="logOut()">Выйти</a></li>
            </ul>
        </div>
    </nav>
</div>
<script>
    const electron = require('electron');
    const Router = require('electron-router');
    let router = Router('WINDOW')

    console.log(router);

    function getAddress() {
        router.send('address')
    }

    function getDeals() {
        router.send('deals')
    }

    function logOut() {
        router.send('logout')
    }


    window.onload = function () {
        router.send('ready')
    }
</script>


```

The routes not working here too. So In my main js I can check user and redirect, also if I mannualy rendering a template , I can not move user between pages! All the requirements which you said is ok for me!

**Comment by m0n0l0c0** [comment]
@gasparyanyur friendly ping :)

**Comment by m0n0l0c0** [comment]
@gasparyanyur, I'm closing this issue, feel free to reopen it if it still doesn't work :)

Best,
Guillermo.
