### ISSUE TITLE
Error thrown during cleanup

### ISSUE THREAD

**Issue by raphinesse** [m0n0l0c0/electron-router#6]
If a window is closed, `Router.prototype.clean` is run in response to the window's `close` event:
https://github.com/m0n0l0c0/electron-router/blob/db1f1fa487bc98552eaa47a18e562fd4e92cc365/router.js#L116-L123

However, `this.clean` is not bound to `this`, so trying to access members of the `_name` property will fail with a `TypeError`:
https://github.com/m0n0l0c0/electron-router/blob/db1f1fa487bc98552eaa47a18e562fd4e92cc365/router.js#L411-L412

A possible solution would be to bind clean to the instance during construction:
```js
      }

      // Bind clean to instance to make it usable as event handler
      this.clean = this.clean.bind(this)

      this._setup(true, cfg)
    }
```

If that sounds feasible to you, I can prepare a PR.

**Comment by m0n0l0c0** [comment]
Hello Raphael,

Thanks for catching that up. Could you provide a MWE?
It looks okay to me, although I would set it up here because it's a setup in the renderer process instance https://github.com/m0n0l0c0/electron-router/blob/db1f1fa487bc98552eaa47a18e562fd4e92cc365/router.js#L117-L124

```js
 win.on('close', this.clean.bind(this)) 
```

Best,
Guillermo

**Comment by raphinesse** [comment]
Your proposed solution would turn this line in `Router.prototype.clean` into a no-op:
https://github.com/m0n0l0c0/electron-router/blob/db1f1fa487bc98552eaa47a18e562fd4e92cc365/router.js#L420

As for a MWE: I'll try to provide one.

**Comment by raphinesse** [comment]
### MWE

```sh
git clone https://gist.github.com/1ae2d7bbb2a8813787e02ec310d7f16b.git electron-router-mwe
cd electron-router-mwe
npm i && npm start
```

Running the above should log (among other things) something similar to the following message:
```
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    source: /xxx/electron-router-mwe/node_modules/electron-router/router.js (412)
```

**Comment by m0n0l0c0** [comment]
Hi @raphinesse,

You're absolutely right with this, I'm going with your solution.

> Your proposed solution would turn this line in `Router.prototype.clean` into a no-op:
> 
> https://github.com/m0n0l0c0/electron-router/blob/db1f1fa487bc98552eaa47a18e562fd4e92cc365/router.js#L420
> 
> As for a MWE: I'll try to provide one.

Thank you for catching this up, I'll update right away

**Comment by raphinesse** [comment]
Thanks for handling this so quickly
