### ISSUE TITLE
Don' need to remove listeners manually?

### ISSUE THREAD

**Issue by Alecyrus** [m0n0l0c0/electron-router#7]

**Comment by m0n0l0c0** [comment]
Hi @Alecyrus,

Yes, you do have to remove listeners manually in most situations, although they're automatigically cleaned for you in the destruction process (when a window is closed or the application is quit).

Regards :)

**Comment by Alecyrus** [comment]
@m0n0l0c0 Good to hear that. Thank you for the nice work, which reduces greatly the complexity  of my work.
