### ISSUE TITLE
Documentation - simple complete example

### ISSUE THREAD

**Issue by logarithms** [m0n0l0c0/electron-router#8]
Need a simple complete working example.
This routing library is tiny, and seems promising,
The documentation also seems to be good, however, one thing missing is a simple but complete working example. Without that, I'm afraid to send a few hours trying to get this to work by trial and error.

**Comment by m0n0l0c0** [comment]
Hi @logarithms,

There is a simple and complete example in the Readme. Furthermore, all methods are well documented and come with a tiny example, that should suffice to get you running.

Best,
Guillermo.
